### ISSUE TITLE
Yo ! Icone Bandcamp ? 

### ISSUE THREAD

**Issue by El-Karlk** [julienc91/karlkmusic#4]
Yo ! 

Il me semble que tu m'avais déjà répondu mais je préfère être sure.

Dans la page discographie, il n'est pas possible de rajouter une icone dans les liens d'écoutes ? J'aurai aimé rajouter un lien bandcamp. https://karlkmusic.bandcamp.com/

Même si l'icone n'est pas celle de bandcamp, ça m'irait ! 

Si pas possible, et bien tanpis ! 

Tcho, bonne journée !

**Comment by julienc91** [comment]
L'icône pour bandcamp est dispo, c'était celle de shazam qui me posait problème.
Mais j'ai besoin de clarification : tu parles de la page "discographie" ou du footer (ou les deux) ? Quelle que soit ta réponse, il faudrait que tu m'indiques l'ordre de priorité que tu souhaites par rapport aux autres liens déjà présents.

**Comment by julienc91** [comment]
Vu ensemble, lien rajouté à la fois dans le footer et dans la discographie après le lien soundcloud.
Pour la partie discographie, les liens sont à rajouter dans le fichier `db.json` comme pour les autres (`discography` -> `tracks` -> `links` -> `bandcamp`).
